languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: true
exclude_paths:
  - "static/fonts/"
  - "static/css/knacss.css"
  - "static/js/moment.js"
  - "static/js/fullcalendar-2.2.6/"
  - "static/js/wysihtml/"
  - "static/js/jquery-2.1.3.min.js"
  - "static/js/jquery-linkify/"
  - "static/js/jquery-ui-1.11.2.custom/"
  - "vendors/"
  - "kansha/alembic/"
  - "tests/"
